package Sonicjumper.EnhancedVisuals.src;

import java.util.Arrays;

import net.minecraft.client.Minecraft;
import net.minecraftforge.common.MinecraftForge;
import Sonicjumper.EnhancedVisuals.src.event.GuiAwarenessRenderer;
import Sonicjumper.EnhancedVisuals.src.event.GuiVisualRenderer;
import Sonicjumper.EnhancedVisuals.src.event.VisualEventHandler;
import Sonicjumper.EnhancedVisuals.src.visual.Visual;
import Sonicjumper.EnhancedVisuals.src.visual.VisualManager;
import Sonicjumper.EnhancedVisuals.src.visual.VisualType;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid=EnhancedVisuals.ID, name=EnhancedVisuals.NAME, version=EnhancedVisuals.VERSION)
@NetworkMod(clientSideRequired=true, serverSideRequired=false)
public class EnhancedVisuals {
	public final static String ID = "SonicVisuals";
	public final static String NAME = "Enhanced Visuals";
	public final static String VERSION = "0.3.0";

	@Instance("SonicVisuals")
    public static EnhancedVisuals instance;
	
	public static Minecraft mc = Minecraft.getMinecraft();
	
	// TODO
	// Make a way to (easily) replace textures with your own (Theme Packs)
	// Make sure to keep everything client side so it still works on servers
	
	public VisualManager visualManager;
    
    public GuiVisualRenderer splatRenderer = new GuiVisualRenderer(mc);
    public GuiAwarenessRenderer awarenessRenderer = new GuiAwarenessRenderer(mc);
    public VisualEventHandler visualEventHandler = new VisualEventHandler(mc);
    public SoundHandler soundHandler = new SoundHandler();
    
    @SidedProxy(clientSide="mods.Sonicjumper.EnhancedVisuals.src.ClientProxy", serverSide="mods.Sonicjumper.EnhancedVisuals.src.ServerProxy")
    public static ServerProxy proxy;
    
    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
    	ModMetadata myMeta = event.getModMetadata();
		myMeta.authorList = Arrays.asList(new String[] { "Sonicjumper" });
		myMeta.autogenerated = false;
		myMeta.description = "Make your Minecraft more realistic with the Enhanced Visuals Mod!";
		
		ConfigCore cc = new ConfigCore(event.getSuggestedConfigurationFile());
		cc.loadConfig();
		
    	proxy.registerClientThings(event);

    	try {
    		Visual initializer = new Visual(VisualType.splatter, 0);
    	} catch(NullPointerException e) {
    		System.out.println("The mod could not load the Visuals, make sure the Theme Pack was installed correctly");
    		e.printStackTrace();
    	}
    	
    	MinecraftForge.EVENT_BUS.register(soundHandler);
    }
    
    @EventHandler
    public void load(FMLInitializationEvent event) {
    	visualManager = new VisualManager();
    }
    
    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
    }
}
